# Coverage dataset per tables

In [1]:
import pandas as pd

In [15]:
#csv schiz
df_schiz=pd.read_csv(r"C:\Users\laiar\Desktop\Classe IDIBAPS\data_sintetica\Data-sintetica\Data-sintetica\src\csv merged\cohort_schizophrenia_sociodemografica.csv")

## 1. Table 4: Derivació

In [2]:
df_4_derivacio=pd.read_csv(r"C:\Users\laiar\Desktop\DATOS_PADRIS_nets\4_689_F_ap_derivacio_sm_Final.csv")

In [3]:
df_4_derivacio.columns

Index(['id', 'idCas', 'Identificador de registre CMBD', 'Unitat Proveïdora',
       'UP_descripcio', 'Data inici assistència', 'Tipus de professional',
       'Tipus_professional_descrip', 'Unitat Proveïdora Destí',
       'Tipus UP Destí'],
      dtype='object')

In [4]:
df_4_derivacio['Data inici assistència'] = pd.to_datetime(df_4_derivacio['Data inici assistència'])
print(df_4_derivacio['Data inici assistència'].min())
print(df_4_derivacio['Data inici assistència'].max())

2015-01-02 00:00:00
2015-12-31 00:00:00

Taula 4 `4_689_F_ap_derivacio_sm_Final.csv` només cobreix l'any `2015`

## 2. Table 5: Comorbiditats

In [5]:
df_5_comorbiditats=pd.read_csv(r"C:\Users\laiar\Desktop\DATOS_PADRIS_nets\5_comorbiditats_cohort_total_2019_2018_Final.csv")
print(df_5_comorbiditats['Any'].min())
print(df_5_comorbiditats['Any'].max())

2018
2019

## 3. Table 6: IMC 2020

In [6]:
df_6_imc=pd.read_csv(r"C:\Users\laiar\Desktop\DATOS_PADRIS_nets\6_imc_2020_Final.csv")
df_6_imc['DATA'] = pd.to_datetime(df_6_imc['DATA'])
print(df_6_imc['DATA'].min())
print(df_6_imc['DATA'].max())

2019-12-31 23:00:00+00:00
2020-11-10 23:00:00+00:00

In [17]:
# Filter for schizophrenia patients
df_4_derivacio_schiz = df_4_derivacio[df_4_derivacio['idCas'].isin(df_schiz['idCas'])].copy()
print(f"Rows: {len(df_4_derivacio_schiz)}") 
print(f"Unique patients: {df_4_derivacio_schiz['idCas'].nunique()}")
df_4_derivacio_schiz.to_csv(r"C:\Users\laiar\Desktop\DATOS_PADRIS_nets\Datos_padris_schizo\6_imc_2020_Final_schizophrenia.csv", index=False)

Rows: 72
Unique patients: 67

## 4. Table 8: Tabac

In [7]:
df_8_tabac=pd.read_csv(r"C:\Users\laiar\Desktop\DATOS_PADRIS_nets\8_tabac_cohort_total_Final.csv")
df_8_tabac['DAT'] = pd.to_datetime(df_8_tabac['DAT'])
df_8_tabac['DBAIXA'] = pd.to_datetime(df_8_tabac['DBAIXA'])

print(df_8_tabac['DAT'].min(), df_8_tabac['DAT'].max())
print(df_8_tabac['DBAIXA'].min(), df_8_tabac['DBAIXA'].max())

1989-12-31 22:00:00+00:00 2017-12-30 22:00:00+00:00
1990-01-28 22:00:00+00:00 2017-12-30 22:00:00+00:00

In [16]:
# Filtrar per schizophrenia
df_8_tabac=df_8_tabac[df_8_tabac["idCas"].isin(df_schiz["idCas"])].copy()
print(f"Rows: {len(df_8_tabac)}")
print(f"Unique patients: {df_8_tabac['idCas'].nunique()}")
df_8_tabac.to_csv(r"C:\Users\laiar\Desktop\DATOS_PADRIS_nets\Datos_padris_schizo\8_tabac_cohort_total_Final_schizophrenia.csv", index=False)

Rows: 10726
Unique patients: 7383

## 5. Table 10: Num visites i far

In [8]:
df_10_num_visites=pd.read_csv(r"C:\Users\laiar\Desktop\DATOS_PADRIS_nets\10_num_visites_i_far_Final.csv")

In [9]:
print(df_10_num_visites["Origen"].min(), df_10_num_visites["Origen"].max())

2018 2019

In [11]:
df_9_2011_2017=pd.read_csv(r"C:\Users\laiar\Desktop\DATOS_PADRIS_nets\9_taula_registre_visites_2011_2017_Final.csv")
# Renombrar columnes de 2018-2019 per matching
df_1819_2018 = df_10_num_visites[df_10_num_visites['Origen'] == 2018].rename(columns={
    'C01_AP': 'C01_AP_2018',
    'C02_AH': 'C02_AH_2018',
    'C04_SMP': 'C04_SMP_2018',
    'C041_CESM': 'C041_CESM_2018',
    'C05_SMH': 'C05_SMH_2018',
    'C06_URG': 'C06_URG_2018',
})[['idCas', 'C01_AP_2018', 'C02_AH_2018', 'C04_SMP_2018', 'C041_CESM_2018', 'C05_SMH_2018', 'C06_URG_2018']]

df_1819_2019 = df_10_num_visites[df_10_num_visites['Origen'] == 2019].rename(columns={
    'C01_AP': 'C01_AP_2019',
    'C02_AH': 'C02_AH_2019',
    'C04_SMP': 'C04_SMP_2019',
    'C041_CESM': 'C041_CESM_2019',
    'C05_SMH': 'C05_SMH_2019',
    'C06_URG': 'C06_URG_2019',
})[['idCas', 'C01_AP_2019', 'C02_AH_2019', 'C04_SMP_2019', 'C041_CESM_2019', 'C05_SMH_2019', 'C06_URG_2019']]

# Afegir a la taula principal
df_final = df_9_2011_2017\
    .merge(df_1819_2018, on='idCas', how='left')\
    .merge(df_1819_2019, on='idCas', how='left')

In [12]:
df_final.head()

,id,idCas,C01_AP_2011,C01_AP_2012,C01_AP_2013,C01_AP_2014,C01_AP_2015,C01_AP_2016,C01_AP_2017,C02_AH_2011,...,C04_SMP_2018,C041_CESM_2018,C05_SMH_2018,C06_URG_2018,C01_AP_2019,C02_AH_2019,C04_SMP_2019,C041_CESM_2019,C05_SMH_2019,C06_URG_2019
0,1,73405420,11,17,14.0,8.0,9.0,5.0,5.0,0.0,...,6,0,0,0,4,0,8,0,0,0
1,2,73405423,18,14,2.0,25.0,12.0,8.0,4.0,0.0,...,2,0,0,0,2,0,4,0,0,0
2,3,73405425,2,0,3.0,0.0,5.0,10.0,5.0,0.0,...,0,0,0,1,0,0,0,0,0,0
3,4,73405426,2,0,3.0,6.0,4.0,3.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,5,73405429,2,1,5.0,3.0,5.0,10.0,2.0,0.0,...,3,10,0,0,1,0,5,0,0,0

In [13]:
df_final.to_csv(r"C:\Users\laiar\Desktop\DATOS_PADRIS_nets\9and10_taula_registre_visites_2011_2019_Final.csv", index=False)

In [14]:
df_schiz=pd.read_csv(r"C:\Users\laiar\Desktop\Classe IDIBAPS\data_sintetica\Data-sintetica\Data-sintetica\src\csv merged\cohort_schizophrenia_sociodemografica.csv")
df_9_2011_2019=df_final[df_final["idCas"].isin(df_schiz["idCas"])].copy()
print(f"Rows: {len(df_9_2011_2019)}")
print(f"Unique patients: {df_9_2011_2019['idCas'].nunique()}")
df_9_2011_2019.to_csv(r"C:\Users\laiar\Desktop\DATOS_PADRIS_nets\Datos_padris_schizo\9_taula_registre_visites_2011_2019_schizophrenia.csv", index=False)

Rows: 9552
Unique patients: 9552

### Reorder columns per years and visits count

In [20]:
# Get all data columns (excluding id and idCas)
data_cols = [col for col in df_9_2011_2019.columns if col not in ["id", "idCas"]]

# Get unique years and variable prefixes
years = sorted(set(col.split("_")[-1] for col in data_cols))
prefixes = sorted(set("_".join(col.split("_")[:-1]) for col in data_cols))

# Reorder columns by year
ordered_cols = ["id", "idCas"]
for year in years:
    year_cols = [col for col in data_cols if col.endswith(year)]
    ordered_cols += year_cols
    # Add total column per year
    df_9_2011_2019[f"TOTAL_{year}"] = df_9_2011_2019[year_cols].sum(axis=1)
    ordered_cols.append(f"TOTAL_{year}")

df_9_2011_2019 = df_9_2011_2019[ordered_cols]
print(df_9_2011_2019.columns.tolist())
print(df_9_2011_2019.head())

['id', 'idCas', 'C01_AP_2011', 'C02_AH_2011', 'C05_SMH_2011', 'C04_SMP_2011', 'C06_URG_2011', 'TOTAL_2011', 'C01_AP_2012', 'C02_AH_2012', 'C05_SMH_2012', 'C04_SMP_2012', 'C06_URG_2012', 'TOTAL_2012', 'C01_AP_2013', 'C02_AH_2013', 'C05_SMH_2013', 'C04_SMP_2013', 'C06_URG_2013', 'TOTAL_2013', 'C01_AP_2014', 'C02_AH_2014', 'C05_SMH_2014', 'C04_SMP_2014', 'C06_URG_2014', 'TOTAL_2014', 'C01_AP_2015', 'C02_AH_2015', 'C05_SMH_2015', 'C04_SMP_2015', 'C06_URG_2015', 'TOTAL_2015', 'C01_AP_2016', 'C02_AH_2016', 'C05_SMH_2016', 'C04_SMP_2016', 'C06_URG_2016', 'TOTAL_2016', 'C01_AP_2017', 'C02_AH_2017', 'C05_SMH_2017', 'C04_SMP_2017', 'C06_URG_2017', 'TOTAL_2017', 'C01_AP_2018', 'C02_AH_2018', 'C04_SMP_2018', 'C041_CESM_2018', 'C05_SMH_2018', 'C06_URG_2018', 'TOTAL_2018', 'C01_AP_2019', 'C02_AH_2019', 'C04_SMP_2019', 'C041_CESM_2019', 'C05_SMH_2019', 'C06_URG_2019', 'TOTAL_2019']
        id     idCas  C01_AP_2011  C02_AH_2011  C05_SMH_2011  C04_SMP_2011  \
75      76  83886730            0          NaN           NaN           NaN
280    281  83888690            0          NaN           NaN           NaN
389    390  83889696            0          NaN           NaN           NaN
538    539  83891376            0          NaN           NaN           NaN
1196  1197  83897358            0          NaN           NaN           NaN

      C06_URG_2011  TOTAL_2011  C01_AP_2012  C02_AH_2012  ...  C05_SMH_2018  \
75             NaN         0.0            8          1.0  ...             0
280            NaN         0.0            3          0.0  ...             0
389            NaN         0.0            0          0.0  ...             0
538            NaN         0.0            0          0.0  ...             0
1196           NaN         0.0           12          0.0  ...             0

      C06_URG_2018  TOTAL_2018  C01_AP_2019  C02_AH_2019  C04_SMP_2019  \
75              11          32           17            0            10
280              0          21           12            0             0
389              0          12            0            0             5
538              1          47           11            0            19
1196             0           9            8            0             9

      C041_CESM_2019  C05_SMH_2019  C06_URG_2019  TOTAL_2019
75                 1             1             4          33
280                0             0             0          12
389                0             0             0           5
538                0             0             1          31
1196               0             0             0          17

[5 rows x 58 columns]

In [22]:
# Fill NaN with 0 and convert to int
for col in data_cols:
    df_9_2011_2019[col] = df_9_2011_2019[col].fillna(0).astype(int)

In [24]:
# Fill NaN with 0 and convert to int for all columns except id and idCas
for col in df_9_2011_2019.columns:
    if col not in ["id", "idCas"]:
        df_9_2011_2019[col] = df_9_2011_2019[col].fillna(0).astype(int)

In [25]:
df_9_2011_2019.to_csv(r"C:\Users\laiar\Desktop\DATOS_PADRIS_nets\Datos_padris_schizo\9_taula_registre_visites_2011_2019_schizophrenia.csv", index=False)

## 6. Table 11: Ap diagnostics (the one we filtered for Schizophrenia)
11_ap_dx_sm_cohort_Final

## 7. SMH Tables 12, 13, 14

In [27]:
df_schiz = pd.read_csv(r"C:\Users\laiar\Desktop\Classe IDIBAPS\data_sintetica\Data-sintetica\Data-sintetica\src\csv merged\cohort_schizophrenia_sociodemografica.csv")['idCas'].unique()
df_12_epi_smh = pd.read_csv(r"C:\Users\laiar\Desktop\DATOS_PADRIS_nets\12_taula_smh_epi_cohort_grup_estudi_Final.csv")
df_13_dx_smh= pd.read_csv(r"C:\Users\laiar\Desktop\DATOS_PADRIS_nets\13_taula_smh_dx_cohort_grup_estudi_Final.csv")
df_14_proc_smh = pd.read_csv(r"C:\Users\laiar\Desktop\DATOS_PADRIS_nets\14_taula_smh_p_cohort_grup_estudi_Final.csv")

df_12_epi_smh_f = df_12_epi_smh[df_12_epi_smh['idCas'].isin(df_schiz)]
df_13_dx_smh_f = df_13_dx_smh[df_13_dx_smh['idCas'].isin(df_schiz)]
df_14_proc_smh_f = df_14_proc_smh[df_14_proc_smh['idCas'].isin(df_schiz)]

In [31]:
# Taula 12 - només dat_ini
df_12_slim = df_12_epi_smh_f[['idCas', 'id_cmbd', 'dat_ini']]

# Taula 13 - desc_dx positions 0-3 in columns
df_13_wide = df_13_dx_smh_f[df_13_dx_smh_f['pos_dx'].isin([1,2,3,4])]\
    .pivot_table(index=['idCas', 'id_cmbd'], columns='pos_dx', values='desc_dx', aggfunc='first')\
    .reindex(columns=[1,2,3,4])\
    .reset_index()

df_13_wide.columns = ['idCas', 'id_cmbd', 'desc_dx_1', 'desc_dx_2', 'desc_dx_3', 'desc_dx_4']

# Afegir pos_dx (és simplement 1,2,3,4 si existeix valor, NaN si no)
for i in [1,2,3,4]:
    df_13_wide.insert(
        df_13_wide.columns.get_loc(f'desc_dx_{i}'),
        f'pos_dx_{i}',
        df_13_wide[f'desc_dx_{i}'].apply(lambda x: i if pd.notna(x) else None)
    )

# Taula 14 - només GZ3ZZZZ, la resta NaN
df_14_slim = df_14_proc_smh_f[df_14_proc_smh_f['cod_proc'] == 'GZ3ZZZZ'][['idCas', 'id_cmbd', 'cod_proc', 'desc_proc']]

# Merge
df_merged_smh = df_12_slim\
    .merge(df_13_wide, on=['idCas', 'id_cmbd'], how='left')\
    .merge(df_14_slim, on=['idCas', 'id_cmbd'], how='left')

In [32]:
df_merged_smh.head(10)

,idCas,id_cmbd,dat_ini,pos_dx_1,desc_dx_1,pos_dx_2,desc_dx_2,pos_dx_3,desc_dx_3,pos_dx_4,desc_dx_4,cod_proc,desc_proc
0,69434608,2019 - 43906,20191113,1.0,Episodi maníac no especificat,2.0,Dependència de l'alcohol amb trastorn no espec...,3.0,Dependència del cànnabis amb trastorn no espec...,4.0,"Dependència dels sedants, els hipnòtics o els ...",GZ3ZZZZ,Control de la medicació
1,75851283,2019 - 2941938,20191107,1.0,Esquizofrènia paranoide,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,75851283,2019 - 22915,20190328,1.0,Esquizofrènia paranoide,2.0,Antecedents personals d'altres afeccions espec...,3.0,Antecedents familiars d'altres trastorns menta...,NaN,NaN,GZ3ZZZZ,Control de la medicació
3,75851283,2019 - 36043,20191011,1.0,Esquizofrènia paranoide,2.0,Cremada de grau no especificat de paret abdomi...,3.0,Abús de cànnabis sense complicacions,4.0,"Abús de sedants, hipnòtics o ansiolítics sense...",GZ3ZZZZ,Control de la medicació
4,76316724,2019 - 44878,20190207,1.0,"Trastorn esquizoafectiu, no especificat",2.0,Abús d'alcohol sense complicacions,3.0,Esquizofrènia paranoide,4.0,Dependència del cànnabis sense complicacions,NaN,NaN
5,76316724,2019 - 13325,20190130,1.0,"Trastorn esquizoafectiu, tipus bipolar",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,76316724,2019 - 45014,20190531,1.0,"Trastorn esquizoafectiu, no especificat",2.0,Dependència del cànnabis sense complicacions,NaN,NaN,NaN,NaN,NaN,NaN
7,76316724,2019 - 44752,20190120,1.0,"Trastorn esquizoafectiu, no especificat",2.0,Psicosi no especificada no causada per una sub...,3.0,Dependència del cànnabis sense complicacions,NaN,NaN,NaN,NaN
8,76521215,2019 - 34351,20190916,1.0,Esquizofrènia paranoide,2.0,Hipertensió (primària) essencial,3.0,Antecedents familiars d'altres trastorns menta...,4.0,"Hipoacúsia no especificada, bilateral",NaN,NaN
9,76521215,2019 - 33456,20190820,1.0,Esquizofrènia paranoide,2.0,Hipertensió (primària) essencial,3.0,Antecedents familiars d'altres trastorns menta...,NaN,NaN,NaN,NaN

In [33]:
df_merged_smh.to_csv(r"C:\Users\laiar\Desktop\DATOS_PADRIS_nets\Datos_padris_schizo\smh_epi_dx_proc_schizophrenia.csv", index=False)

In [34]:
df_merged_smh.value_counts()

idCas      id_cmbd       dat_ini   pos_dx_1  desc_dx_1                                pos_dx_2  desc_dx_2                                                                                            pos_dx_3  desc_dx_3                                                                                            pos_dx_4  desc_dx_4                                                        cod_proc  desc_proc
93604931   2018 - 8976   20180124  1.0       Trastorn esquizoafectiu, no especificat  2.0       Trastorn de la personalitat no especificat                                                           3.0       Abús de cànnabis sense complicacions                                                                 4.0       Abús d'alcohol sense complicacions                               GZ3ZZZZ   Control de la medicació    4
100334209  2018 - 25492  20171129  1.0       Trastorn esquizoafectiu, no especificat  2.0       Apnea del son no especificada                                                                        3.0       Dependència de la nicotina, no especificat, sense complicacions                                      4.0       Obesitat no especificada                                         GZ3ZZZZ   Control de la medicació    3
87996703   2019 - 45135  20190424  1.0       Esquizofrènia paranoide                  2.0       Dependència de l'alcohol en remissió                                                                 3.0       Dependència de la nicotina, no especificat, sense complicacions                                      4.0       Dependència de la cocaïna en remissió                            GZ3ZZZZ   Control de la medicació    2
94248858   2018 - 29069  20180821  1.0       Esquizofrènia paranoide                  2.0       Abús d'alcohol sense complicacions                                                                   3.0       Abús de cocaïna sense complicacions                                                                  4.0       Dependència de la nicotina, no especificat, sense complicacions  GZ3ZZZZ   Control de la medicació    2
87293353   2019 - 15375  20190128  1.0       Esquizofrènia no especificada            2.0       Diabetis mellitus de tipus 2 amb hiperglucèmia                                                       3.0       Trastorn del metabolisme de les lipoproteïnes no especificat                                         4.0       Hipertensió (primària) essencial                                 GZ3ZZZZ   Control de la medicació    2
                                                                                                                                                                                                                                                                                                                                                                                                                                   ..
100611894  2019 - 32243  20190301  1.0       Esquizofrènia residual                   2.0       Altres trastorns de la personalitat específics                                                       3.0       Dependència de la nicotina, no especificat, amb altres trastorns induïts per la nicotina             4.0       Dependència de l'alcohol en remissió                             GZ3ZZZZ   Control de la medicació    1
100619264  2018 - 10084  20180209  1.0       Esquizofrènia paranoide                  2.0       Úlcera crònica no causada per pressió, altres parts de peu no especificat, gravetat no especificada  3.0       Altres tipus especificats de diabetis mellitus amb polineuropatia diabètica                          4.0       Ús d'insulina a llarg termini (actual)                           GZ3ZZZZ   Control de la medicació    1
           2018 - 5548   20180113  1.0       Esquizofrènia residual                   2.0       Diabetis mellitus de tipus 2 amb hiperglucèmia                                                       3.0       Úlcera crònica no causada per pressió, altres parts de peu no especificat, gravetat no especificada  4.0       Malaltia degenerativa del sistema nerviós no especificada        GZ3ZZZZ   Control de la medicació    1
100625376  2018 - 18733  20180222  1.0       Altres tipus d'esquizofrènia             2.0       Dependència de l'alcohol sense complicacions                                                         3.0       Quist ovàric no especificat, costat no especificat                                                   4.0       Lumbàlgia                                                        GZ3ZZZZ   Control de la medicació    1
75851283   2019 - 36043  20191011  1.0       Esquizofrènia paranoide                  2.0       Cremada de grau no especificat de paret abdominal, assistència inicial                               3.0       Abús de cànnabis sense complicacions                                                                 4.0       Abús de sedants, hipnòtics o ansiolítics sense complicacions     GZ3ZZZZ   Control de la medicació    1
Name: count, Length: 1365, dtype: int64

In [35]:
df_merged_smh['any_cmbd'] = df_merged_smh['id_cmbd'].str.extract(r'(\d{4})')
print(df_merged_smh['any_cmbd'].value_counts().sort_index())

any_cmbd
2010    1921
2011    2220
2012    2443
2013    2586
2014    2706
2015    2932
2016    3062
2017    3008
2018    3229
2019    2650
Name: count, dtype: int64

## 8. URG Tables 16, 17, 18

In [37]:
# Carregar taules
df_16_urg_epi = pd.read_csv(r"C:\Users\laiar\Desktop\DATOS_PADRIS_nets\16_cmbd_urg_episodis_final_Final.csv")
df_17_urg_dx = pd.read_csv(r"C:\Users\laiar\Desktop\DATOS_PADRIS_nets\17_cmbd_urg_diagnostics_cohort_grup_estudi_Final.csv")
df_18_urg_proc = pd.read_csv(r"C:\Users\laiar\Desktop\DATOS_PADRIS_nets\18_cmbd_urg_p_cohort_grup_estudi_Final.csv")

# Filtrar per cohort
df_16_f = df_16_urg_epi[df_16_urg_epi['idCas'].isin(df_schiz)]
df_17_f = df_17_urg_dx[df_17_urg_dx['idCas'].isin(df_schiz)]
df_18_f = df_18_urg_proc[df_18_urg_proc['idCas'].isin(df_schiz)]

# Taula 16 - columnes seleccionades
df_16_slim = df_16_f[['idCas', 'id_cmbd', 'dat_ini', 'dat_fi', 'cod_proc_ing', 'desc_proc_ing', 'cod_tip_up_desti', 'desc_tip_up_desti']]

# Taula 17 - pivot desc_dx posicions 1-4
df_17_wide = df_17_f[df_17_f['pos_dx'].isin([1,2,3,4])]\
    .pivot_table(index=['idCas', 'id_cmbd'], columns='pos_dx', values='desc_dx', aggfunc='first')\
    .reindex(columns=[1,2,3,4])\
    .reset_index()
df_17_wide.columns = ['idCas', 'id_cmbd', 'desc_dx_1', 'desc_dx_2', 'desc_dx_3', 'desc_dx_4']
for i in [1,2,3,4]:
    df_17_wide.insert(df_17_wide.columns.get_loc(f'desc_dx_{i}'), f'pos_dx_{i}',
        df_17_wide[f'desc_dx_{i}'].apply(lambda x: i if pd.notna(x) else None))

# Taula 18 - pivot desc_proc posicions 0-3
df_18_wide = df_18_f[df_18_f['pos_proc'].isin([0,1,2,3])]\
    .pivot_table(index=['idCas', 'id_cmbd'], columns='pos_proc', values='desc_proc', aggfunc='first')\
    .reindex(columns=[0,1,2,3])\
    .reset_index()
df_18_wide.columns = ['idCas', 'id_cmbd', 'desc_proc_0', 'desc_proc_1', 'desc_proc_2', 'desc_proc_3']
for i in [0,1,2,3]:
    df_18_wide.insert(df_18_wide.columns.get_loc(f'desc_proc_{i}'), f'pos_proc_{i}',
        df_18_wide[f'desc_proc_{i}'].apply(lambda x: i if pd.notna(x) else None))

# Merge
df_merged_urg = df_16_slim\
    .merge(df_17_wide, on=['idCas', 'id_cmbd'], how='left')\
    .merge(df_18_wide, on=['idCas', 'id_cmbd'], how='left')

In [38]:
df_merged_urg.head(10)

,idCas,id_cmbd,dat_ini,dat_fi,cod_proc_ing,desc_proc_ing,cod_tip_up_desti,desc_tip_up_desti,pos_dx_1,desc_dx_1,...,pos_dx_4,desc_dx_4,pos_proc_0,desc_proc_0,pos_proc_1,desc_proc_1,pos_proc_2,desc_proc_2,pos_proc_3,desc_proc_3
0,69434608,2019 - 525662003,20191112,20191112,1,Domicili o residència social,6063,ASSISTÈNCIA SALUT MENTAL - HOSPITALITZACIÓ,1.0,Psicosi no especificada no causada per una sub...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,75851283,2019 - 491262242,20190327,20190328,1,Domicili o residència social,6063,ASSISTÈNCIA SALUT MENTAL - HOSPITALITZACIÓ,1.0,Al·lucinacions auditives,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,75851283,2019 - 520244000,20191010,20191010,2,Trasllat des d'un hospital general d'aguts o h...,6063,ASSISTÈNCIA SALUT MENTAL - HOSPITALITZACIÓ,1.0,Trastorn de conducta no especificat,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,76316724,2019 - 485976393,20190224,20190224,Y,Sense especificar,6063,ASSISTÈNCIA SALUT MENTAL - HOSPITALITZACIÓ,1.0,Trastorn mental no psicòtic no especificat,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,76316724,2019 - 488920351,20190313,20190313,Y,Sense especificar,6063,ASSISTÈNCIA SALUT MENTAL - HOSPITALITZACIÓ,1.0,Trastorn mental no psicòtic no especificat,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,76316724,2019 - 488922940,20190313,20190313,1,Domicili o residència social,6063,ASSISTÈNCIA SALUT MENTAL - HOSPITALITZACIÓ,1.0,Trastorn d'ansietat no especificat,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,76316724,2019 - 478181834,20190120,20190120,Y,Sense especificar,6063,ASSISTÈNCIA SALUT MENTAL - HOSPITALITZACIÓ,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,77558423,2019 - 497861517,20190510,20190511,2,Trasllat des d'un hospital general d'aguts o h...,6064,ASSISTÈNCIA SALUT MENTAL - HOSPITAL DE DIA,1.0,Esquizofrènia no especificada,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,83706898,2019 - 510305723,20190730,20190731,2,Trasllat des d'un hospital general d'aguts o h...,6063,ASSISTÈNCIA SALUT MENTAL - HOSPITALITZACIÓ,1.0,Esquizofrènia paranoide,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,83886730,2015 - 273872054,20150611,20150611,Y,SEM,6063,ASSISTÈNCIA SALUT MENTAL - HOSPITALITZACIÓ,1.0,Trastorn mental no psicòtic inepecificat,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
print(df_17_f['pos_dx'].value_counts().sort_index())

pos_dx
1    2825
2     383
3     116
4      43
Name: count, dtype: int64

In [40]:
df_merged_urg.to_csv(r"C:\Users\laiar\Desktop\DATOS_PADRIS_nets\Datos_padris_schizo\urg_epi_dx_proc_schizophrenia.csv", index=False)

In [41]:
df_merged_urg['any_cmbd'] = df_merged_urg['id_cmbd'].str.extract(r'(\d{4})')
print(df_merged_urg['any_cmbd'].value_counts().sort_index())

any_cmbd
2014    463
2015    564
2016    501
2017    481
2018    601
2019    593
2020      2
Name: count, dtype: int64